apex-mdapi/src/objects/News__c.object
<CustomObject>
    <description>News Used in B2B Commerce</description>
    <fields>
        <fullName>Layout__c</fullName>
        <defaultValue>&apos;Center&apos;</defaultValue>
        <label>Layout</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Left</fullName>
                </value>
                <value>
                    <fullName>Center</fullName>
                    <default>true</default>
                    <label>Center</label>
                </value>
                <value>
                    <fullName>Right</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Draft&apos;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visibility__c</fullName>
        <inlineHelpText>- Public: visible to all user (including guests)
- Private: visible to logged-in users

If it&apos;s set to private, you can resize the visibility by creating an audience.</inlineHelpText>
        <label>Visibility</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VisibleCarousel__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visible In Carousel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VisibleNewsSection__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visible In News Section</label>
        <type>Checkbox</type>
    </fields>
    <label>News</label>
    <nameField>
        <label>News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-mdapi/src/objects/NewsLocalized__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>CarouselImageUrl__c</fullName>
        <label>Carousel Image Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DetailImageUrl__c</fullName>
        <label>Detail Image Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>News__c</fullName>
        <label>News</label>
        <referenceTo>News__c</referenceTo>
        <relationshipName>NewsLocalized</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>News Localized</label>
    <nameField>
        <label>NewsLocalized Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News Localized</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

apex-mdapi/src/classes/B2BNewsController_TEST.cls
/**
 * Created by winardo on 3/19/2024.
 */

@IsTest
private class B2BNewsController_TEST {

	@TestSetup
	public static void prepareScenario(){
		Account a = new Account();
		a.Name = 'Test';
		insert a;

	}

	@IsTest
	public static void test_retrieveLastNews(){
		News__c n = createNews();

		NewsLocalized__c nl = [SELECT Id FROM NewsLocalized__c WHERE News__c = :n.Id LIMIT 1];
		nl.Title__c = 'TEST';
		nl.Body__c = 'TEST';
		nl.CarouselImageUrl__c = 'TEST';
		nl.DetailImageUrl__c = 'TEST';

		update nl;

		n.Visibility__c = 'Public';
		n.Status__c = 'Published';
		n.VisibleCarousel__c = true;
		n.VisibleNewsSection__c = true;

		update n;

		Account a = [SELECT Id FROM Account LIMIT 1];

		B2BNewsController.retrieveLastNews(a.Id, 'en_US', true);
		B2BNewsController.retrieveCarouselNews(a.Id, 'en_US', true);
		B2BNewsController.retrieveAllNews(a.Id, 'en_US', true, 0, 3, null);
		B2BNewsController.retrieveAllNews(a.Id, '', true, 0, 3,'News');
		B2BNewsController.retrieveNews(n.Id, 'en_US', true);
		B2BNewsController.getTopicPicklistValues();

	}

	public static News__c createNews(){
		News__c n = new News__c();
		n.Name = 'Test';
		n.Layout__c = 'Center';
		n.Status__c = 'Draft';
		n.Visibility__c = 'Private';
		n.StartDate__c = Date.today();
		insert n;

		return n;
	}


}