apex-mdapi/src/objects/News__c.object
<CustomObject>
    <description>News Used in B2B Commerce</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Layout__c</fullName>
        <defaultValue>&apos;Center&apos;</defaultValue>
        <label>Layout</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Left</fullName>
                </value>
                <value>
                    <fullName>Center</fullName>
                    <default>true</default>
                    <label>Center</label>
                </value>
                <value>
                    <fullName>Right</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Draft&apos;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visibility__c</fullName>
        <inlineHelpText>- Public: visible to all user (including guests)
- Private: visible to logged-in users

If it&apos;s set to private, you can resize the visibility by creating an audience.</inlineHelpText>
        <label>Visibility</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>News</label>
    <nameField>
        <label>News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-mdapi/src/objects/NewsLocalized__c.object
<CustomObject>
    <fields>
        <fullName>News__c</fullName>
        <label>News</label>
        <referenceTo>News__c</referenceTo>
        <relationshipName>NewsLocalized</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>News Localized</label>
    <nameField>
        <label>NewsLocalized Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News Localized</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

apex-mdapi/src/classes/News_TEST.cls
/**
 * Created by winardo on 3/8/2024.
 */

@IsTest
private inherited sharing class News_TEST {

	@TestSetup
	public static void prepareScenario(){
		Account a = new Account();
		a.Name = 'Test';
		insert a;
	}

	@IsTest
	public static void creteNews(){
		News__c n = createNews();

		try{
			delete [SELECT ID FROM NewsLocalized__c WHERE News__c = :n.Id];
		} catch(Exception e){
			//Need come here - Default localization cant be deleted
			Assert.isTrue(true);
		}

		try{
			n.Status__c = 'Pubblish';
			update n;
		} catch(Exception e){
			//Need come here - Pubblish with nothing must be handled
			Assert.isTrue(true);
		}
	}

	@IsTest
	public static void testLocalized(){
		News__c n = createNews();
		Id localized = [SELECT Id FROM NewsLocalized__c WHERE News__c = :n.Id LIMIT 1].Id;
		B2BNewsLocalizedController.retrieveNewsLocalized(localized);

		ContentVersion contentVersion = new ContentVersion(
			Title          = 'a picture',
			PathOnClient   = 'Pic.jpg',
			VersionData    = Blob.valueOf('Test Content'),
			IsMajorVersion = true);
		insert contentVersion;

		ContentVersion contentVersion2 = new ContentVersion(
			Title          = 'a picture',
			PathOnClient   = 'Pic.jpg',
			VersionData    = Blob.valueOf('Test Content'),
			IsMajorVersion = true);
		insert contentVersion2;

		List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

		B2BNewsLocalizedController.createAttachment(localized, documents[0].Id, B2BNewsLocalizedController.ModeEnum.Carousel.name());
		B2BNewsLocalizedController.createAttachment(localized, documents[1].Id, B2BNewsLocalizedController.ModeEnum.Detail.name());
		B2BNewsLocalizedController.deleteAttachment(localized, B2BNewsLocalizedController.ModeEnum.Carousel.name());
		B2BNewsLocalizedController.deleteAttachment(localized, B2BNewsLocalizedController.ModeEnum.Detail.name());
	}

	@IsTest
	public static void expireNews(){
		News__c n = createNews();
		n.EndDate__c = Date.today().addDays(-1);
		update n;

		Test.startTest();
		try{
			Batch_DeactivateExpiredNews.scheduleMe();
			Batch_DeactivateExpiredNews b1 = new Batch_DeactivateExpiredNews();
			Database.executeBatch(b1);
		} catch(Exception e){
			//Need come here - Pubblish with nothing must be handled
			Assert.isTrue(true);
		}
		Test.stopTest();
	}

	public static News__c createNews(){
		News__c n = new News__c();
		n.Name = 'Test';
		n.Layout__c = 'Center';
		n.Status__c = 'Draft';
		n.Visibility__c = 'Private';
		n.StartDate__c = Date.today();
		insert n;

		return n;
	}

}