apex-mdapi/src/objects/News__c.object
<CustomObject>
    <description>News Used in B2B Commerce</description>
    <fields>
        <fullName>CarouselOrder__c</fullName>
        <label>Carousel Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Layout__c</fullName>
        <defaultValue>&apos;Center&apos;</defaultValue>
        <label>Layout</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Left</fullName>
                </value>
                <value>
                    <fullName>Center</fullName>
                    <default>true</default>
                    <label>Center</label>
                </value>
                <value>
                    <fullName>Right</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NewsSectionOrder__c</fullName>
        <label>News Section Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Draft&apos;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <defaultValue>&apos;News&apos;</defaultValue>
        <label>Topic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>News</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visibility__c</fullName>
        <inlineHelpText>- Public: visible to all user (including guests)
- Private: visible to logged-in users

If it&apos;s set to private, you can resize the visibility by creating an audience.</inlineHelpText>
        <label>Visibility</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VisibleCarousel__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visible In Carousel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VisibleNewsSection__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visible In News Section</label>
        <type>Checkbox</type>
    </fields>
    <label>News</label>
    <nameField>
        <label>News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-mdapi/src/objects/NewsLocalized__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>CarouselContentDocumentId__c</fullName>
        <label>Carousel Content Document Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CarouselImageUrl__c</fullName>
        <label>Carousel Image Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DetailContentDocumentId__c</fullName>
        <label>Detail Content Document Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DetailImageUrl__c</fullName>
        <label>Detail Image Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Locale__c</fullName>
        <label>Locale</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>en_US</fullName>
                    <label>English</label>
                </value>
                <value>
                    <fullName>fr</fullName>
                    <label>French</label>
                </value>
                <value>
                    <fullName>de</fullName>
                    <label>German</label>
                </value>
                <value>
                    <fullName>it</fullName>
                    <label>Italian</label>
                </value>
                <value>
                    <fullName>es</fullName>
                    <label>Spanish</label>
                </value>
                <value>
                    <fullName>pt-BR</fullName>
                    <label>Portoguese</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>News__c</fullName>
        <label>News</label>
        <referenceTo>News__c</referenceTo>
        <relationshipName>NewsLocalized</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VideoPosition__c</fullName>
        <label>Video position</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On top</fullName>
                </value>
                <value>
                    <fullName>On bottom</fullName>
                    <default>true</default>
                    <label>On bottom</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>YuotubeLink__c</fullName>
        <inlineHelpText>Youtube video Code.

To retrieve the YouTube video code from a YouTube URL, follow these steps:

1. Copy the full URL of the YouTube video you want to extract the code from.
2. Paste the URL into your web browser&apos;s address bar.
3. Look for the part of the URL after &quot;v=&quot;.
4. The code following &quot;v=&quot; is the YouTube video code.
In this example (https://www.youtube.com/watch?v=0vQO9RcEyJA), the YouTube video code is &quot;0vQO9RcEyJA&quot;.</inlineHelpText>
        <label>Yuotube Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>News Localized</label>
    <nameField>
        <label>NewsLocalized Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News Localized</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

apex-mdapi/src/classes/NewsDAO.cls
/** AUTOTEST: News_TEST,B2BNewsController_TEST **/
/**
 * Created by winardo on 3/8/2024.
 */

public inherited sharing class NewsDAO {

	public static List<NewsLocalized__c> getNewsLocalizedByNewsIds(Set<Id> newsIds, Boolean onlyDefault){
		System.debug(LoggingLevel.DEBUG, 'NewsDAO::getNewsLocalizedByNewsIds::newsIds::' + newsIds.size());
		System.debug(LoggingLevel.DEBUG, 'NewsDAO::getNewsLocalizedByNewsIds::onlyDefault::' + onlyDefault);

		String soql = 'SELECT Id, Locale__c, Body__c, Title__c, News__c, CarouselImageUrl__c, DetailImageUrl__c ' +
			'FROM NewsLocalized__c ' +
			'WHERE News__c IN :newsIds ';
		if(onlyDefault){
			soql += ' AND IsDefault__c = TRUE';
		}

		System.debug(LoggingLevel.FINEST, 'NewsDAO::getNewsLocalizedByNewsIds::soql::' + soql);
		return Database.query(soql);
	}

	public static NewsLocalized__c getNewsLocalizedById(Id newsLocalizedId){
		return [
			SELECT Id, DetailImageUrl__c, CarouselImageUrl__c,
				CarouselContentDocumentId__c, DetailContentDocumentId__c
			FROM NewsLocalized__c
			WHERE Id = :newsLocalizedId LIMIT 1
		];
	}

	public static News__c retrieveNewsById(Id newsId){
		return [
			SELECT Id, StartDate__c, Topic__c, NewsSectionOrder__c, CarouselOrder__c, Layout__c FROM News__c WHERE Id = :newsId LIMIT 1
		];
	}

	public static List<News__c> retrieveNews(B2BNewsController.NewsType newsType, B2BNewsController.UserLoggedType userType, Contact c, Integer lim, Integer off, String topic){
		String visibilityStatment = getVisibilityStatment(userType);

		Date today = Date.today();

		String soql = 'SELECT Id, NewsSectionOrder__c, CarouselOrder__c, Layout__c, StartDate__c, Topic__c, EndDate__c ' +
			' FROM News__c ' +
			' WHERE (Status__c = \'Published\' AND ' + visibilityStatment +
			' AND ((StartDate__c <= :today AND (EndDate__c >= :today OR EndDate__c = null))) ' +
			' AND ';

		if (newsType == B2BNewsController.NewsType.DETAIL) {
			soql += ' VisibleNewsSection__c = TRUE';

			if (topic != null && !topic.equalsIgnoreCase('All') && !String.isBlank(topic)) {
				soql += ' AND Topic__c = :topic';
			}

			soql += ') ORDER BY NewsSectionOrder__c ASC';
		} else {
			soql += ' VisibleCarousel__c = TRUE )';
			soql += ' ORDER BY CarouselOrder__c ASC ';
		}

		if(lim != null){
			soql += ' LIMIT :lim ';
			if(off != null){
				soql += ' OFFSET :off ';
			}
		}

		System.debug('::NewsDAO::retrieveNews::topic' + topic);
		System.debug('::NewsDAO::retrieveNews::' + soql);

		return Database.query(soql);
	}

	private static String getVisibilityStatment(B2BNewsController.UserLoggedType userType) {
		String visibilityStatment = ' (Visibility__c = \'Public\' ';
		if(userType != B2BNewsController.UserLoggedType.GUEST) {
			visibilityStatment += 'OR (Visibility__c = \'Private\')';
		}
		visibilityStatment += ')';
		return visibilityStatment;
	}

	public static Integer countNews(B2BNewsController.NewsType newsType, B2BNewsController.UserLoggedType userType, String topic) {
		String visibilityStatment = getVisibilityStatment(userType);

		Date today = Date.today();
		String soql = 'SELECT COUNT(ID) ' +
			' FROM News__c ' +
			' WHERE (Status__c = \'Published\' AND ' + visibilityStatment +
			' AND ((StartDate__c <= :today AND (EndDate__c >= :today OR EndDate__c = null))) ' +
			' AND ';

		if(newsType == B2BNewsController.NewsType.DETAIL){
			soql += ' VisibleNewsSection__c = TRUE ';

			if (topic != null && !topic.equalsIgnoreCase('All') && !String.isBlank(topic)) {
				soql += ' AND Topic__c = :topic';
			}

			soql += ')';
		} else {
			soql += ' VisibleCarousel__c = TRUE )';
		}

		List<AggregateResult> ar = Database.query(soql);
		return ar.isEmpty() ? 0 : Integer.valueOf(ar.get(0).get('expr0'));
	}

	public static List<NewsLocalized__c> retrieveLocalization(Set<Id> newsIds, String locale){
		return [
			SELECT Id, DetailImageUrl__c, CarouselImageUrl__c, Title__c, Body__c, News__c, IsDefault__c, Locale__c, YuotubeLink__c, VideoPosition__c
			FROM NewsLocalized__c
			WHERE News__c IN :newsIds
				AND (IsDefault__c = TRUE OR Locale__c = :locale)
		];
	}

}